using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Microsoft.CodeAnalysis.Text;

namespace Library.SourceGenerator.Tests
{
    public class DbContextGeneratorTests
    {
        [Fact]
        public async Task GeneratesSessionForDbContext()
        {
            var someDbContextDefinition = @"
            using Library;

            public class Blog {}
            public class Post {}

            public class BloggingContext : DbContext
            {
                public BloggingContext(DbContextOptions options) : base(options) {}

                public IDbSet<Blog> Blogs { get; set; }
                public IDbSet<Post> Posts { get; set; }
            }";

            var expected = 
@"// <auto-generated/>
#nullable enable
public sealed class BloggingContextSession : global::Library.DbContextSession<BloggingContext>
{
    private readonly BloggingContext _dbContext;

    public BloggingContextSession(BloggingContext dbContext) : base(dbContext)
    {
        _dbContext = dbContext;
    }

    public async global::System.Threading.Tasks.Task SaveChangesAsync()
    {
    }
}
";

            var test = new CSharpSourceGeneratorTest<SourceGenerator.DbContextGenerator, XUnitVerifier>
            {
                TestState =
                {
                    Sources = { someDbContextDefinition },
                    ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
                    GeneratedSources =
                    {
                        (typeof(SourceGenerator.DbContextGenerator), "BloggingContextSession.g.cs", 
                            SourceText.From(expected, Encoding.UTF8)),
                    },
                },
            };

            test.TestState.AdditionalReferences.Add(MetadataReference.CreateFromFile(typeof(DbContext).Assembly.Location));
            await test.RunAsync();

            var generatedSource = test.TestState.GeneratedSources
                .Select(g => g.content.ToString())
                .FirstOrDefault();

            Assert.NotNull(generatedSource);
        }
    }
}