using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace MongoZen.SourceGenerator.Tests;

public class DbContextSessionsGeneratorTests
{
    private static CSharpCompilation CreateCompilation(string source)
    {
        var references = new List<MetadataReference>();

        // Add .NET runtime assemblies
        var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        foreach (var dll in new[]
                 {
                     "System.Runtime.dll",
                     "System.Collections.dll",
                     "System.Threading.Tasks.dll",
                     "netstandard.dll",
                 })
        {
            var path = Path.Combine(runtimeDir, dll);
            if (File.Exists(path))
            {
                references.Add(MetadataReference.CreateFromFile(path));
            }
        }

        references.Add(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));

        // MongoZen reference (brings DbContext, IDbSet<T>, etc.)
        references.Add(MetadataReference.CreateFromFile(typeof(DbContext).Assembly.Location));

        var tree = CSharpSyntaxTree.ParseText(source);
        return CSharpCompilation.Create(
            "TestAssembly",
            new[] { tree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    [Fact]
    public void GeneratesSessionForDbContext()
    {
        var source = @"
using MongoZen;

public class Blog {}
public class Post {}

public class BloggingContext : DbContext
{
    public BloggingContext(DbContextOptions options) : base(options) {}

    public IDbSet<Blog> Blogs { get; set; }
    public IDbSet<Post> Posts { get; set; }
}";

        var expected =
            @"// <auto-generated/>
#nullable enable
using System.Threading.Tasks;
using MongoZen;

public sealed class BloggingContextSession : MongoZen.DbContextSession<BloggingContext>
{
    public BloggingContextSession(BloggingContext dbContext) : this(dbContext, startTransaction: true)
    {
    }

    public BloggingContextSession(BloggingContext dbContext, bool startTransaction) : base(dbContext, startTransaction)
    {
        unsafe {
            Blogs = new MongoZen.MutableDbSet<Blog>(((BloggingContext)GetDbContext()).Blogs, () => Transaction, this, (entity, arena) => { var ptr = arena.Alloc((nuint)System.Runtime.CompilerServices.Unsafe.SizeOf<Blog_Shadow>()); ref var s = ref System.Runtime.CompilerServices.Unsafe.AsRef<Blog_Shadow>(ptr); s.From(entity, arena); return (System.IntPtr)ptr; }, (entity, ptr) => { ref var s = ref System.Runtime.CompilerServices.Unsafe.AsRef<Blog_Shadow>((void*)ptr); return s.IsDirty(entity); }, GetDbContext().Options.Conventions);
            Posts = new MongoZen.MutableDbSet<Post>(((BloggingContext)GetDbContext()).Posts, () => Transaction, this, (entity, arena) => { var ptr = arena.Alloc((nuint)System.Runtime.CompilerServices.Unsafe.SizeOf<Post_Shadow>()); ref var s = ref System.Runtime.CompilerServices.Unsafe.AsRef<Post_Shadow>(ptr); s.From(entity, arena); return (System.IntPtr)ptr; }, (entity, ptr) => { ref var s = ref System.Runtime.CompilerServices.Unsafe.AsRef<Post_Shadow>((void*)ptr); return s.IsDirty(entity); }, GetDbContext().Options.Conventions);        }
    }

    public MongoZen.IMutableDbSet<Blog> Blogs { get; }
    public MongoZen.IMutableDbSet<Post> Posts { get; }

    public override void Store<TEntity>(TEntity entity) where TEntity : class
    {
        if (entity is Blog e0)
        {
            Blogs.Store(e0);
        }
        else if (entity is Post e1)
        {
            Posts.Store(e1);
        }
        else
        {
            throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
        }
    }

    public override void Delete<TEntity>(TEntity entity) where TEntity : class
    {
        if (entity is Blog e0)
        {
            Blogs.Delete(e0);
        }
        else if (entity is Post e1)
        {
            Posts.Delete(e1);
        }
        else
        {
            throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
        }
    }

    public override void Delete<TEntity>(object id) where TEntity : class
    {
        if (typeof(TEntity) == typeof(Blog))
        {
            Blogs.Delete(id);
        }
        else if (typeof(TEntity) == typeof(Post))
        {
            Posts.Delete(id);
        }
        else
        {
            throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
        }
    }

    public MongoZen.IMutableDbSet<TEntity> Query<TEntity>() where TEntity : class
    {
        if (typeof(TEntity) == typeof(Blog))
        {
            return (MongoZen.IMutableDbSet<TEntity>)(object)Blogs;
        }
        else if (typeof(TEntity) == typeof(Post))
        {
            return (MongoZen.IMutableDbSet<TEntity>)(object)Posts;
        }
        else
        {
            throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
        }
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public void Add<TEntity>(TEntity entity) where TEntity : class
    {
        Store(entity);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public void Attach<TEntity>(TEntity entity) where TEntity : class
    {
        if (entity is Blog e0)
        {
            Blogs.Attach(e0);
        }
        else if (entity is Post e1)
        {
            Posts.Attach(e1);
        }
        else
        {
            throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
        }
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public void Remove<TEntity>(TEntity entity) where TEntity : class
    {
        Delete(entity);
    }

    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public void Remove<TEntity>(object id) where TEntity : class
    {
        Delete<TEntity>(id);
    }

    public async ValueTask<TEntity?> LoadAsync<TEntity>(object id, System.Threading.CancellationToken cancellationToken = default) where TEntity : class
    {
        if (typeof(TEntity) == typeof(Blog))
        {
            return (TEntity?)(object?)await Blogs.LoadAsync(id, cancellationToken);
        }
        else if (typeof(TEntity) == typeof(Post))
        {
            return (TEntity?)(object?)await Posts.LoadAsync(id, cancellationToken);
        }
        else
        {
            throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
        }
    }

    public MongoZen.IMutableDbSet<TEntity> Include<TEntity>(System.Linq.Expressions.Expression<System.Func<TEntity, object?>> path) where TEntity : class
    {
        if (typeof(TEntity) == typeof(Blog))
        {
            return (MongoZen.IMutableDbSet<TEntity>)(object)Blogs.Include((System.Linq.Expressions.Expression<System.Func<Blog, object?>>)(object)path);
        }
        else if (typeof(TEntity) == typeof(Post))
        {
            return (MongoZen.IMutableDbSet<TEntity>)(object)Posts.Include((System.Linq.Expressions.Expression<System.Func<Post, object?>>)(object)path);
        }
        else
        {
            throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
        }
    }

    public MongoZen.IMutableDbSet<TEntity> Include<TEntity, TInclude>(System.Linq.Expressions.Expression<System.Func<TEntity, object?>> path) where TEntity : class where TInclude : class
    {
        if (typeof(TEntity) == typeof(Blog))
        {
            return (MongoZen.IMutableDbSet<TEntity>)(object)Blogs.Include<TInclude>((System.Linq.Expressions.Expression<System.Func<Blog, object?>>)(object)path);
        }
        else if (typeof(TEntity) == typeof(Post))
        {
            return (MongoZen.IMutableDbSet<TEntity>)(object)Posts.Include<TInclude>((System.Linq.Expressions.Expression<System.Func<Post, object?>>)(object)path);
        }
        else
        {
            throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
        }
    }

    public async ValueTask SaveChangesAsync(System.Threading.CancellationToken cancellationToken = default)
    {
        EnsureTransactionActive();
        try
        {
            await ((MongoZen.IInternalMutableDbSet)Blogs).CommitAsync(Transaction, cancellationToken);
            await ((MongoZen.IInternalMutableDbSet)Posts).CommitAsync(Transaction, cancellationToken);

            await CommitTransactionAsync();

            Blogs.Advanced.ClearTracking();
            Posts.Advanced.ClearTracking();
            ClearTracking();
        }
        catch
        {
            if (Transaction.IsActive)
            {
                await AbortTransactionAsync();
            }

            await DisposeAsync();
            throw;
        }
    }
}
";

        var compilation = CreateCompilation(source);
        var generator = new DbContextSessionsGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            compilation, out var outputCompilation, out var diagnostics);

        var result = driver.GetRunResult();
        Assert.Single(result.Results);

        var generatorResult = result.Results[0];
        Assert.Empty(generatorResult.Diagnostics);
        Assert.Single(generatorResult.GeneratedSources);

        var generatedSource = generatorResult.GeneratedSources[0];
        Assert.Equal("BloggingContextSession.g.cs", generatedSource.HintName);

        var actualText = generatedSource.SourceText.ToString();
        Assert.Equal(Normalize(expected), Normalize(actualText));
    }

    [Fact]
    public void GeneratesSessionForDbContextWithNamespaceAndMixedProperties()
    {
        var source = @"
using MongoZen;

namespace MyNamespace
{
    public class User {}

    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions options) : base(options) {}

        public IDbSet<User> Users { get; set; }
        public string ConnectionString { get; set; } // Should be ignored
    }
}";

        var expected =
            @"// <auto-generated/>
#nullable enable
using System.Threading.Tasks;
using MongoZen;

namespace MyNamespace
{
    public sealed class MyContextSession : MongoZen.DbContextSession<MyNamespace.MyContext>
    {
        public MyContextSession(MyNamespace.MyContext dbContext) : this(dbContext, startTransaction: true)
        {
        }

        public MyContextSession(MyNamespace.MyContext dbContext, bool startTransaction) : base(dbContext, startTransaction)
        {
            unsafe {
                Users = new MongoZen.MutableDbSet<MyNamespace.User>(((MyNamespace.MyContext)GetDbContext()).Users, () => Transaction, this, (entity, arena) => { var ptr = arena.Alloc((nuint)System.Runtime.CompilerServices.Unsafe.SizeOf<MyNamespace.User_Shadow>()); ref var s = ref System.Runtime.CompilerServices.Unsafe.AsRef<MyNamespace.User_Shadow>(ptr); s.From(entity, arena); return (System.IntPtr)ptr; }, (entity, ptr) => { ref var s = ref System.Runtime.CompilerServices.Unsafe.AsRef<MyNamespace.User_Shadow>((void*)ptr); return s.IsDirty(entity); }, GetDbContext().Options.Conventions);
            }
        }

        public MongoZen.IMutableDbSet<MyNamespace.User> Users { get; }

        public override void Store<TEntity>(TEntity entity) where TEntity : class
        {
            if (entity is MyNamespace.User e0)
            {
                Users.Store(e0);
            }
            else
            {
                throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
            }
        }

        public override void Delete<TEntity>(TEntity entity) where TEntity : class
        {
            if (entity is MyNamespace.User e0)
            {
                Users.Delete(e0);
            }
            else
            {
                throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
            }
        }

        public override void Delete<TEntity>(object id) where TEntity : class
        {
            if (typeof(TEntity) == typeof(MyNamespace.User))
            {
                Users.Delete(id);
            }
            else
            {
                throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
            }
        }

        public MongoZen.IMutableDbSet<TEntity> Query<TEntity>() where TEntity : class
        {
            if (typeof(TEntity) == typeof(MyNamespace.User))
            {
                return (MongoZen.IMutableDbSet<TEntity>)(object)Users;
            }
            else
            {
                throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
            }
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public void Add<TEntity>(TEntity entity) where TEntity : class
        {
            Store(entity);
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public void Attach<TEntity>(TEntity entity) where TEntity : class
        {
            if (entity is MyNamespace.User e0)
            {
                Users.Attach(e0);
            }
            else
            {
                throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
            }
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public void Remove<TEntity>(TEntity entity) where TEntity : class
        {
            Delete(entity);
        }

        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public void Remove<TEntity>(object id) where TEntity : class
        {
            Delete<TEntity>(id);
        }

        public async ValueTask<TEntity?> LoadAsync<TEntity>(object id, System.Threading.CancellationToken cancellationToken = default) where TEntity : class
        {
            if (typeof(TEntity) == typeof(MyNamespace.User))
            {
                return (TEntity?)(object?)await Users.LoadAsync(id, cancellationToken);
            }
            else
            {
                throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
            }
        }

        public MongoZen.IMutableDbSet<TEntity> Include<TEntity>(System.Linq.Expressions.Expression<System.Func<TEntity, object?>> path) where TEntity : class
        {
            if (typeof(TEntity) == typeof(MyNamespace.User))
            {
                return (MongoZen.IMutableDbSet<TEntity>)(object)Users.Include((System.Linq.Expressions.Expression<System.Func<MyNamespace.User, object?>>)(object)path);
            }
            else
            {
                throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
            }
        }

        public MongoZen.IMutableDbSet<TEntity> Include<TEntity, TInclude>(System.Linq.Expressions.Expression<System.Func<TEntity, object?>> path) where TEntity : class where TInclude : class
        {
            if (typeof(TEntity) == typeof(MyNamespace.User))
            {
                return (MongoZen.IMutableDbSet<TEntity>)(object)Users.Include<TInclude>((System.Linq.Expressions.Expression<System.Func<MyNamespace.User, object?>>)(object)path);
            }
            else
            {
                throw new System.ArgumentException($""Entity type {typeof(TEntity).Name} is not part of this DbContext."");
            }
        }

        public async ValueTask SaveChangesAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            EnsureTransactionActive();
            try
            {
                await ((MongoZen.IInternalMutableDbSet)Users).CommitAsync(Transaction, cancellationToken);

                await CommitTransactionAsync();

                Users.Advanced.ClearTracking();
                ClearTracking();
            }
            catch
            {
                if (Transaction.IsActive)
                {
                    await AbortTransactionAsync();
                }

                await DisposeAsync();
                throw;
            }
        }
    }
}
";

        var compilation = CreateCompilation(source);
        var generator = new DbContextSessionsGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            compilation, out var outputCompilation, out var diagnostics);

        var result = driver.GetRunResult();
        Assert.Single(result.Results);

        var generatorResult = result.Results[0];
        Assert.Empty(generatorResult.Diagnostics);
        Assert.Single(generatorResult.GeneratedSources);

        var generatedSource = generatorResult.GeneratedSources[0];
        Assert.Equal("MyContextSession.g.cs", generatedSource.HintName);

        var actualText = generatedSource.SourceText.ToString();
        Assert.Equal(Normalize(expected), Normalize(actualText));
    }

    private static string Normalize(string s) => System.Text.RegularExpressions.Regex.Replace(s, @"\s+", "");
}
