using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MongoZen.SourceGenerator.Tests;

public class DbContextExtensionsGeneratorTests
{
    private static CSharpCompilation CreateCompilation(params string[] sources)
    {
        var references = new List<MetadataReference>();

        // Add .NET runtime assemblies
        var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        foreach (var dll in new[]
                 {
                     "System.Runtime.dll",
                     "System.Collections.dll",
                     "System.Threading.Tasks.dll",
                     "netstandard.dll",
                 })
        {
            var path = Path.Combine(runtimeDir, dll);
            if (File.Exists(path))
            {
                references.Add(MetadataReference.CreateFromFile(path));
            }
        }

        references.Add(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));

        // MongoZen reference (brings DbContext, IDbSet<T>, etc.)
        references.Add(MetadataReference.CreateFromFile(typeof(DbContext).Assembly.Location));

        var trees = sources.Select(s => CSharpSyntaxTree.ParseText(s)).ToArray();
        return CSharpCompilation.Create(
            "TestAssembly",
            trees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    [Fact]
    public void GeneratesStartSessionExtensionForMultipleDbContexts()
    {
        // Both contexts are in the global namespace — they share one static class with no namespace wrapper.
        var source = @"
using MongoZen;

public class Blog {}
public class Post {}
public class Thread {}

public class BloggingContext : DbContext
{
    public BloggingContext(DbContextOptions options) : base(options) {}
    public IDbSet<Blog> Blogs { get; set; }
    public IDbSet<Post> Posts { get; set; }
}

public class ForumContext : DbContext
{
    public ForumContext(DbContextOptions options) : base(options) {}
    public IDbSet<Thread> Threads { get; set; }
}
";
        var sessionStubs = @"
public class BloggingContextSession
{
    public BloggingContextSession(BloggingContext context) {}
    public BloggingContextSession(BloggingContext context, bool startTransaction) {}
}

public class ForumContextSession
{
    public ForumContextSession(ForumContext context) {}
    public ForumContextSession(ForumContext context, bool startTransaction) {}
}
";

        // Global-namespace contexts → no namespace block, one shared static class.
        var expected = @"// <auto-generated/>
#nullable enable
using MongoZen;

public static class DbContextSessionExtensions
{
    public static BloggingContextSession StartSession(this BloggingContext context)
        => new BloggingContextSession(context);

    public static BloggingContextSession StartSession(this BloggingContext context, bool startTransaction)
        => new BloggingContextSession(context, startTransaction);

    public static ForumContextSession StartSession(this ForumContext context)
        => new ForumContextSession(context);

    public static ForumContextSession StartSession(this ForumContext context, bool startTransaction)
        => new ForumContextSession(context, startTransaction);

}

";

        var compilation = CreateCompilation(source, sessionStubs);
        var generator = new DbContextExtensionsGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            compilation, out var outputCompilation, out var diagnostics);

        var result = driver.GetRunResult();
        Assert.Single(result.Results);

        var generatorResult = result.Results[0];
        Assert.Empty(generatorResult.Diagnostics);
        Assert.Single(generatorResult.GeneratedSources);

        var generatedSource = generatorResult.GeneratedSources[0];
        Assert.Equal("DbContextSessionExtensions.g.cs", generatedSource.HintName);

        var actualText = generatedSource.SourceText.ToString();
        Assert.Equal(Normalize(expected), Normalize(actualText));
    }

    [Fact]
    public void GeneratesStartSessionExtensionForDbContextInNamespace()
    {
        // Context is in MyNamespace — extension class must be wrapped in that namespace block.
        var source = @"
using MongoZen;

namespace MyNamespace
{
    public class Blog {}

    public class BloggingContext : DbContext
    {
        public BloggingContext(DbContextOptions options) : base(options) {}
        public IDbSet<Blog> Blogs { get; set; }
    }
}
";
        var sessionStubs = @"
namespace MyNamespace
{
    public class BloggingContextSession
    {
        public BloggingContextSession(BloggingContext context) {}
        public BloggingContextSession(BloggingContext context, bool startTransaction) {}
    }
}
";

        // Namespace-scoped context → extension class is wrapped in the same namespace.
        var expected = @"// <auto-generated/>
#nullable enable
using MongoZen;

namespace MyNamespace
{
    public static class DbContextSessionExtensions
    {
        public static MyNamespace.BloggingContextSession StartSession(this MyNamespace.BloggingContext context)
            => new MyNamespace.BloggingContextSession(context);

        public static MyNamespace.BloggingContextSession StartSession(this MyNamespace.BloggingContext context, bool startTransaction)
            => new MyNamespace.BloggingContextSession(context, startTransaction);

    }
}

";

        var compilation = CreateCompilation(source, sessionStubs);
        var generator = new DbContextExtensionsGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            compilation, out var outputCompilation, out var diagnostics);

        var result = driver.GetRunResult();
        Assert.Single(result.Results);

        var generatorResult = result.Results[0];
        Assert.Empty(generatorResult.Diagnostics);
        Assert.Single(generatorResult.GeneratedSources);

        var generatedSource = generatorResult.GeneratedSources[0];
        Assert.Equal("DbContextSessionExtensions.g.cs", generatedSource.HintName);

        var actualText = generatedSource.SourceText.ToString();
        Assert.Equal(Normalize(expected), Normalize(actualText));
    }

    private static string Normalize(string s) => s.Replace("\r\n", "\n");
}
