using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Microsoft.CodeAnalysis.Text;

namespace MongoZen.SourceGenerator.Tests
{
    public class DbContextSessionsGeneratorTests
    {
        [Fact]
        public async Task GeneratesSessionForDbContext()
        {
            var someDbContextDefinition = @"
            using MongoZen;

            public class Blog {}
            public class Post {}

            public class BloggingContext : DbContext
            {
                public BloggingContext(DbContextOptions options) : base(options) {}

                public IDbSet<Blog> Blogs { get; set; }
                public IDbSet<Post> Posts { get; set; }
            }";

            var expected =
                @"// <auto-generated/>
#nullable enable
using System.Threading.Tasks;
using MongoZen;

public sealed class BloggingContextSession : MongoZen.DbContextSession<BloggingContext>
{
    public BloggingContextSession(BloggingContext dbContext) : base(dbContext)
    {
        Blogs = new MongoZen.MutableDbSet<Blog>(_dbContext.Blogs, _dbContext.Options.Conventions);
        Posts = new MongoZen.MutableDbSet<Post>(_dbContext.Posts, _dbContext.Options.Conventions);
    }

    public MongoZen.IMutableDbSet<Blog> Blogs { get; }
    public MongoZen.IMutableDbSet<Post> Posts { get; }

    public async ValueTask SaveChangesAsync()
    {
        await Blogs.CommitAsync();
        await Posts.CommitAsync();
    }
}
";

            var test = new CSharpSourceGeneratorTest<SourceGenerator.DbContextSessionsGenerator, XUnitVerifier>
            {
                TestState =
                {
                    Sources = { someDbContextDefinition },
                    ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
                    GeneratedSources =
                    {
                        (typeof(SourceGenerator.DbContextSessionsGenerator), "BloggingContextSession.g.cs",
                            SourceText.From(expected, Encoding.UTF8)),
                    },
                },
            };

            test.TestState.AdditionalReferences.Add(
                MetadataReference.CreateFromFile(typeof(DbContext).Assembly.Location));

            // act & assert
            await test.RunAsync();
        }

        [Fact]
        public async Task GeneratesSessionForDbContextWithNoDbSets()
        {
            var source = @"
            using MongoZen;

            public class EmptyContext : DbContext
            {
                public EmptyContext(DbContextOptions options) : base(options) {}
            }";

            var expected =
                @"// <auto-generated/>
#nullable enable
using System.Threading.Tasks;
using MongoZen;

public sealed class EmptyContextSession : MongoZen.DbContextSession<EmptyContext>
{
    public EmptyContextSession(EmptyContext dbContext) : base(dbContext)
    {
    }

    public async ValueTask SaveChangesAsync()
    {
    }
}
";

            var test = new CSharpSourceGeneratorTest<SourceGenerator.DbContextSessionsGenerator, XUnitVerifier>
            {
                TestState =
                {
                    Sources = { source },
                    ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
                    GeneratedSources =
                    {
                        (typeof(SourceGenerator.DbContextSessionsGenerator), "EmptyContextSession.g.cs",
                            SourceText.From(expected, Encoding.UTF8)),
                    },
                },
            };

            test.TestState.AdditionalReferences.Add(
                MetadataReference.CreateFromFile(typeof(DbContext).Assembly.Location));

            await test.RunAsync();
        }

        [Fact]
        public async Task GeneratesSessionForDbContextWithNamespaceAndMixedProperties()
        {
            var someDbContextDefinition = @"
            using MongoZen;

            namespace MyNamespace 
            {
                public class User {}
                
                public class MyContext : DbContext
                {
                    public MyContext(DbContextOptions options) : base(options) {}

                    public IDbSet<User> Users { get; set; }
                    public string ConnectionString { get; set; } // Should be ignored
                }
            }";

            var expected =
                @"// <auto-generated/>
#nullable enable
using System.Threading.Tasks;
using MongoZen;

namespace MyNamespace
{
    public sealed class MyContextSession : MongoZen.DbContextSession<MyNamespace.MyContext>
    {
        public MyContextSession(MyNamespace.MyContext dbContext) : base(dbContext)
        {
            Users = new MongoZen.MutableDbSet<MyNamespace.User>(_dbContext.Users, _dbContext.Options.Conventions);
        }

        public MongoZen.IMutableDbSet<MyNamespace.User> Users { get; }

        public async ValueTask SaveChangesAsync()
        {
            await Users.CommitAsync();
        }
    }
}
";

            var test = new CSharpSourceGeneratorTest<SourceGenerator.DbContextSessionsGenerator, XUnitVerifier>
            {
                TestState =
                {
                    Sources = { someDbContextDefinition },
                    ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
                    GeneratedSources =
                    {
                        (typeof(SourceGenerator.DbContextSessionsGenerator), "MyContextSession.g.cs",
                            SourceText.From(expected, Encoding.UTF8)),
                    },
                },
            };

            test.TestState.AdditionalReferences.Add(
                MetadataReference.CreateFromFile(typeof(DbContext).Assembly.Location));

            // act & assert
            await test.RunAsync();
        }
    }
}
