using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MongoZen.SourceGenerator.Tests;

public class DbContextSessionsGeneratorTests
{
    private static CSharpCompilation CreateCompilation(string source)
    {
        var references = new List<MetadataReference>();

        // Add .NET runtime assemblies
        var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;
        foreach (var dll in new[]
                 {
                     "System.Runtime.dll",
                     "System.Collections.dll",
                     "System.Threading.Tasks.dll",
                     "netstandard.dll",
                 })
        {
            var path = Path.Combine(runtimeDir, dll);
            if (File.Exists(path))
            {
                references.Add(MetadataReference.CreateFromFile(path));
            }
        }

        references.Add(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));

        // MongoZen reference (brings DbContext, IDbSet<T>, etc.)
        references.Add(MetadataReference.CreateFromFile(typeof(DbContext).Assembly.Location));

        var tree = CSharpSyntaxTree.ParseText(source);
        return CSharpCompilation.Create(
            "TestAssembly",
            new[] { tree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    [Fact]
    public void GeneratesSessionForDbContext()
    {
        var source = @"
using MongoZen;

public class Blog {}
public class Post {}

public class BloggingContext : DbContext
{
    public BloggingContext(DbContextOptions options) : base(options) {}

    public IDbSet<Blog> Blogs { get; set; }
    public IDbSet<Post> Posts { get; set; }
}";

        var expected =
            @"// <auto-generated/>
#nullable enable
using System.Threading.Tasks;
using MongoZen;

public sealed class BloggingContextSession : MongoZen.DbContextSession<BloggingContext>
{
    public BloggingContextSession(BloggingContext dbContext) : base(dbContext)
    {
        Blogs = new MongoZen.MutableDbSet<Blog>(_dbContext.Blogs, _dbContext.Options.Conventions);
        Posts = new MongoZen.MutableDbSet<Post>(_dbContext.Posts, _dbContext.Options.Conventions);
    }

    public MongoZen.IMutableDbSet<Blog> Blogs { get; }
    public MongoZen.IMutableDbSet<Post> Posts { get; }

    public async ValueTask SaveChangesAsync()
    {
        EnsureTransactionActive();
        try
        {
            await Blogs.CommitAsync(Transaction);
            await Posts.CommitAsync(Transaction);

            await CommitTransactionAsync();

            Blogs.ClearTracking();
            Posts.ClearTracking();
        }
        catch
        {
            if (Transaction.IsActive)
            {
                await AbortTransactionAsync();
            }

            throw;
        }
    }
}
";

        var compilation = CreateCompilation(source);
        var generator = new DbContextSessionsGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            compilation, out var outputCompilation, out var diagnostics);

        var result = driver.GetRunResult();
        Assert.Single(result.Results);

        var generatorResult = result.Results[0];
        Assert.Empty(generatorResult.Diagnostics);
        Assert.Single(generatorResult.GeneratedSources);

        var generatedSource = generatorResult.GeneratedSources[0];
        Assert.Equal("BloggingContextSession.g.cs", generatedSource.HintName);

        var actualText = generatedSource.SourceText.ToString();
        Assert.Equal(Normalize(expected), Normalize(actualText));
    }

    [Fact]
    public void GeneratesSessionForDbContextWithNamespaceAndMixedProperties()
    {
        var source = @"
using MongoZen;

namespace MyNamespace
{
    public class User {}

    public class MyContext : DbContext
    {
        public MyContext(DbContextOptions options) : base(options) {}

        public IDbSet<User> Users { get; set; }
        public string ConnectionString { get; set; } // Should be ignored
    }
}";

        var expected =
            @"// <auto-generated/>
#nullable enable
using System.Threading.Tasks;
using MongoZen;

namespace MyNamespace
{
    public sealed class MyContextSession : MongoZen.DbContextSession<MyNamespace.MyContext>
    {
        public MyContextSession(MyNamespace.MyContext dbContext) : base(dbContext)
        {
            Users = new MongoZen.MutableDbSet<MyNamespace.User>(_dbContext.Users, _dbContext.Options.Conventions);
        }

        public MongoZen.IMutableDbSet<MyNamespace.User> Users { get; }

        public async ValueTask SaveChangesAsync()
        {
            EnsureTransactionActive();
            try
            {
                await Users.CommitAsync(Transaction);

                await CommitTransactionAsync();

                Users.ClearTracking();
            }
            catch
            {
                if (Transaction.IsActive)
                {
                    await AbortTransactionAsync();
                }

                throw;
            }
        }
    }
}
";

        var compilation = CreateCompilation(source);
        var generator = new DbContextSessionsGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(
            compilation, out var outputCompilation, out var diagnostics);

        var result = driver.GetRunResult();
        Assert.Single(result.Results);

        var generatorResult = result.Results[0];
        Assert.Empty(generatorResult.Diagnostics);
        Assert.Single(generatorResult.GeneratedSources);

        var generatedSource = generatorResult.GeneratedSources[0];
        Assert.Equal("MyContextSession.g.cs", generatedSource.HintName);

        var actualText = generatedSource.SourceText.ToString();
        Assert.Equal(Normalize(expected), Normalize(actualText));
    }

    private static string Normalize(string s) => s.Replace("\r\n", "\n");
}
