using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MongoZen.SourceGenerator;

/// <summary>
/// Generates an optimized override for <c>InitializeDbSets()</c> for every
/// concrete class that derives from MongoZen.DbContext.
/// This eliminates the need for reflection at runtime when initializing DbSets.
/// </summary>
[Generator]
public sealed class DbContextInitializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var dbContextSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, ct) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(cds, ct) is not INamedTypeSymbol symbol)
                    {
                        return null;
                    }

                    return !Utils.InheritsFrom(symbol, "DbContext") ? null :
                        symbol.IsAbstract ? null : symbol;
                })
            .Where(static symbol => symbol is not null)!
            .Select(static (symbol, _) => symbol!);

        var compilationAndClasses = context.CompilationProvider.Combine(dbContextSymbols.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var (_, classes) = source;

            foreach (var ctxSymbol in classes)
            {
                spc.AddSource(
                    $"{ctxSymbol.Name}.Initializer.g.cs",
                    SourceText.From(GenerateInitializer(ctxSymbol), Encoding.UTF8));
            }
        });
    }

    private static string GenerateInitializer(INamedTypeSymbol ctxSymbol)
    {
        var ns = ctxSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : ctxSymbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using MongoZen;");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.Append("namespace ").AppendLine(ns).AppendLine("{");
        }

        var indent = ns is null ? string.Empty : "    ";
        var indent2 = indent + "    ";
        
        sb.Append(indent).Append("public partial class ").AppendLine(ctxSymbol.Name);
        sb.Append(indent).AppendLine("{");
        
        sb.Append(indent2).AppendLine("protected override void InitializeDbSets()");
        sb.Append(indent2).AppendLine("{");
        
        sb.Append(indent2).AppendLine("    if (Options.UseInMemory)");
        sb.Append(indent2).AppendLine("    {");
        
        foreach (var member in ctxSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.Type is INamedTypeSymbol { IsGenericType: true } namedType &&
                (namedType.Name == "IDbSet" || namedType.AllInterfaces.Any(i => i.Name == "IDbSet")))
            {
                var entityType = namedType.TypeArguments[0].ToDisplayString();
                sb.Append(indent2).Append("        this.").Append(member.Name)
                  .Append(" = new MongoZen.InMemoryDbSet<").Append(entityType).AppendLine(">();");
            }
        }
        
        sb.Append(indent2).AppendLine("    }");
        sb.Append(indent2).AppendLine("    else");
        sb.Append(indent2).AppendLine("    {");
        sb.Append(indent2).AppendLine("        if (Options.Mongo == null) throw new System.InvalidOperationException(\"Mongo database not configured.\");");

        foreach (var member in ctxSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.Type is INamedTypeSymbol { IsGenericType: true } namedType &&
                (namedType.Name == "IDbSet" || namedType.AllInterfaces.Any(i => i.Name == "IDbSet")))
            {
                var entityType = namedType.TypeArguments[0].ToDisplayString();
                sb.Append(indent2).Append("        this.").Append(member.Name)
                  .Append(" = new MongoZen.DbSet<").Append(entityType).Append(">(Options.Mongo.GetCollection<").Append(entityType).Append(">(\"").Append(member.Name).AppendLine("\"), Options.Conventions);");
            }
        }
        
        sb.Append(indent2).AppendLine("    }");
        sb.Append(indent2).AppendLine("}");

        sb.Append(indent).AppendLine("}");
        
        if (ns is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
