using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
// ReSharper disable ComplexConditionExpression

namespace MongoZen.SourceGenerator;

[Generator]
public sealed class DbContextExtensionsGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initializes the incremental generation pipeline for DbContext session extension methods.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var dbContextSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, ct) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(cds, ct) is not INamedTypeSymbol symbol)
                    {
                        return null;
                    }

                    var compilation = ctx.SemanticModel.Compilation;
                    return !Utils.InheritsFrom(symbol, "DbContext") ? null :
                        symbol.IsAbstract ? null : symbol;
                })
            .Where(static symbol => symbol is not null)!
            .Collect();

        context.RegisterSourceOutput(dbContextSymbols, static (spc, ctxSymbols) =>
        {
            if (ctxSymbols.Length > 0)
            {
                var output = GenerateSessionExtensions(ctxSymbols);
                spc.AddSource("DbContextSessionExtensions.g.cs", SourceText.From(output, Encoding.UTF8));
            }
        });
    }

    private static string GenerateSessionExtensions(IEnumerable<INamedTypeSymbol> dbContextTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using MongoZen;");
        sb.AppendLine();

        // Group by namespace so contexts in the same namespace share one static class.
        // Each group is wrapped in its own namespace block to avoid global-namespace pollution
        // and CS0433 collisions when two projects both define DbContext subclasses.
        var byNamespace = dbContextTypes
            .GroupBy(t => t.ContainingNamespace.IsGlobalNamespace
                ? null
                : t.ContainingNamespace.ToDisplayString());

        foreach (var group in byNamespace)
        {
            var ns = group.Key;
            if (ns is not null)
            {
                sb.Append("namespace ").AppendLine(ns);
                sb.AppendLine("{");
            }

            var indent = ns is null ? string.Empty : "    ";
            sb.Append(indent).AppendLine("public static class DbContextSessionExtensions");
            sb.Append(indent).AppendLine("{");

            foreach (var type in group)
            {
                var contextFullName = type.ToDisplayString();
                var sessionFullName = $"{contextFullName}Session";

                sb.Append(indent).Append("    public static ").Append(sessionFullName)
                  .Append(" StartSession(this ").Append(contextFullName)
                  .AppendLine(" context)");
                sb.AppendLine($"{indent}        => new {sessionFullName}(context);");
                sb.AppendLine();
                sb.Append(indent).Append("    public static ").Append(sessionFullName)
                  .Append(" StartSession(this ").Append(contextFullName)
                  .AppendLine(" context, bool startTransaction)");
                sb.AppendLine($"{indent}        => new {sessionFullName}(context, startTransaction);");
                sb.AppendLine();
            }

            sb.Append(indent).AppendLine("}");
            if (ns is not null)
            {
                sb.AppendLine("}");
            }
            sb.AppendLine();
        }

        return sb.ToString();
    }
}
