using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MongoZen.SourceGenerator;

/// <summary>
/// Generates a unit‑of‑work façade ― <c>{DbContextName}Session</c> ― for every
/// concrete class that derives from MongoZen.DbContext.
/// The session exposes one <c>IMutableDbSet&lt;T&gt;</c> per <c>IDbSet&lt;T&gt;</c>
/// property found on the underlying context and a <c>SaveChangesAsync()</c>
/// method that calls <c>CommitAsync()</c> on each of those mutable sets.
/// </summary>
[Generator]
public sealed class DbContextSessionsGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initializes the incremental generation pipeline for DbContext session wrapper classes.
    /// </summary>
    /// <param name="context">The generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var dbContextSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, ct) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(cds, ct) is not INamedTypeSymbol symbol)
                    {
                        return null;
                    }

                    var compilation = ctx.SemanticModel.Compilation;
                    return !Utils.InheritsFrom(symbol, "DbContext") ? null :
                        symbol.IsAbstract ? null : symbol;
                })
            .Where(static symbol => symbol is not null)!
            .Select(static (symbol, _) => symbol!);

        var compilationAndClasses = context.CompilationProvider.Combine(dbContextSymbols.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var (_, classes) = source;

            foreach (var ctxSymbol in classes)
            {
                spc.AddSource(
                    $"{ctxSymbol.Name}Session.g.cs",
                    SourceText.From(GenerateSessionClass(ctxSymbol), Encoding.UTF8));
            }
        });
    }

    private static string GenerateSessionClass(INamedTypeSymbol ctxSymbol)
    {
        var ns = ctxSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : ctxSymbol.ContainingNamespace.ToDisplayString();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using MongoZen;");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.Append("namespace ").AppendLine(ns).AppendLine("{");
        }

        var indent = ns is null ? string.Empty : "    ";
        var indent2 = indent + "    ";
        sb.Append(indent).Append("public sealed class ").Append(ctxSymbol.Name).Append("Session");
        sb.Append(" : MongoZen.DbContextSession<").Append(ctxSymbol.ToDisplayString()).AppendLine(">");
        sb.Append(indent).AppendLine("{");

        var mutableProps = new List<(string Name, string EntityType)>();

        foreach (var member in ctxSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.Type is INamedTypeSymbol { IsGenericType: true } namedType &&
                namedType.Name == "IDbSet")
            {
                var entityType = namedType.TypeArguments[0].ToDisplayString();
                mutableProps.Add((member.Name, entityType));
            }
        }

        // Constructor
        sb.Append(indent2).Append("public ").Append(ctxSymbol.Name).Append("Session(")
          .Append(ctxSymbol.ToDisplayString()).AppendLine(" dbContext) : this(dbContext, startTransaction: true)");
        sb.Append(indent2).AppendLine("{");
        sb.Append(indent2).AppendLine("}");
        sb.AppendLine();
        sb.Append(indent2).Append("public ").Append(ctxSymbol.Name).Append("Session(")
          .Append(ctxSymbol.ToDisplayString()).AppendLine(" dbContext, bool startTransaction) : base(dbContext, startTransaction)");
        sb.Append(indent2).AppendLine("{");
        sb.Append(indent2).AppendLine("    unsafe {");

        foreach (var prop in mutableProps)
        {
        sb.Append(indent2).Append("        ").Append(prop.Name)
        .Append(" = new MongoZen.MutableDbSet<")
        .Append(prop.EntityType).Append(">(")
        .Append("_dbContext.").Append(prop.Name).Append(", ")
        .Append("() => Transaction, ")
        .Append("this, ") // Pass the session as ISessionTracker
        .Append("(entity, arena) => { var s = default(").Append(prop.EntityType).Append("_Shadow); s.From(entity, arena); return (System.IntPtr)System.Runtime.CompilerServices.Unsafe.AsPointer(ref s); }, ")
        .Append("(entity, ptr) => { ref var s = ref System.Runtime.CompilerServices.Unsafe.AsRef<").Append(prop.EntityType).Append("_Shadow>((void*)ptr); return s.IsDirty(entity); }, ")
        .Append("_dbContext.Options.Conventions")
        .AppendLine(");");
        }
        sb.Append(indent2).AppendLine("    }");
        sb.Append(indent2).AppendLine("}");
        sb.AppendLine();

        foreach (var prop in mutableProps)
        {
            sb.Append(indent2).Append("public MongoZen.IMutableDbSet<")
              .Append(prop.EntityType).Append("> ")
              .Append(prop.Name).AppendLine(" { get; }");
        }

        // SaveChangesAsync
        sb.AppendLine();
        sb.Append(indent2).AppendLine("public async ValueTask SaveChangesAsync()");
        sb.Append(indent2).AppendLine("{");
        sb.Append(indent2).AppendLine("    EnsureTransactionActive();");
        sb.Append(indent2).AppendLine("    try");
        sb.Append(indent2).AppendLine("    {");
        foreach (var prop in mutableProps)
        {
            sb.Append(indent2).Append("        await ").Append(prop.Name).AppendLine(".CommitAsync(Transaction);");
        }

        sb.AppendLine();
        sb.Append(indent2).AppendLine("        await CommitTransactionAsync();");
        sb.AppendLine();

        // Clear tracking only after successful commit
        foreach (var prop in mutableProps)
        {
            sb.Append(indent2).Append("        ").Append(prop.Name).AppendLine(".ClearTracking();");
        }

        sb.Append(indent2).AppendLine("    }");
        sb.Append(indent2).AppendLine("    catch");
        sb.Append(indent2).AppendLine("    {");
        sb.Append(indent2).AppendLine("        if (Transaction.IsActive)");
        sb.Append(indent2).AppendLine("        {");
        sb.Append(indent2).AppendLine("            await AbortTransactionAsync();");
        sb.Append(indent2).AppendLine("        }");
        sb.AppendLine();
        sb.Append(indent2).AppendLine("        await DisposeAsync();");
        sb.Append(indent2).AppendLine("        throw;");
        sb.Append(indent2).AppendLine("    }");
        sb.Append(indent2).AppendLine("}");

        sb.Append(indent).AppendLine("}");
        if (ns is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
