using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
// ReSharper disable ComplexConditionExpression

namespace MongoZen.SourceGenerator;

/// <summary>
/// Generates extension methods that create session wrappers for DbContext types.
/// </summary>
[Generator]
public sealed class DbContextExtensionsGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var dbContextSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, ct) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(cds, ct) is not INamedTypeSymbol symbol)
                    {
                        return null;
                    }

                    var compilation = ctx.SemanticModel.Compilation;
                    return !Utils.InheritsFrom(symbol, "MongoZen.DbContext", compilation) ? null :
                        symbol.IsAbstract ? null : symbol;
                })
            .Where(static symbol => symbol is not null)!
            .Collect();

        context.RegisterSourceOutput(dbContextSymbols, static (spc, ctxSymbols) =>
        {
            if(ctxSymbols.Length > 0)
            {
                var output = GenerateSessionExtensions(ctxSymbols);
                spc.AddSource("DbContextSessionExtensions.g.cs", SourceText.From(output, Encoding.UTF8));
            }
        });
    }

    private static string GenerateSessionExtensions(IEnumerable<INamedTypeSymbol> dbContextTypes)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using MongoZen;");
        sb.AppendLine();
        sb.AppendLine("public static class DbContextSessionExtensions");
        sb.AppendLine("{");

        foreach (var type in dbContextTypes)
        {
            var contextFullName = type.ToDisplayString();
            var sessionFullName = $"{contextFullName}Session";

            sb.Append("    public static ").Append(sessionFullName)
              .Append(" StartSession(this ").Append(contextFullName)
              .AppendLine(" context)");
            sb.AppendLine($"        => new {sessionFullName}(context);");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
