using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MongoZen.SourceGenerator;

[Generator]
public sealed class ShadowStructsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all entity types used in IDbSet<T> within a DbContext
        var entityTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, ct) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(cds, ct) is not INamedTypeSymbol symbol)
                    {
                        return ImmutableArray<INamedTypeSymbol>.Empty;
                    }

                    if (!Utils.InheritsFrom(symbol, "DbContext") || symbol.IsAbstract)
                    {
                        return ImmutableArray<INamedTypeSymbol>.Empty;
                    }

                    var types = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
                    foreach (var member in symbol.GetMembers().OfType<IPropertySymbol>())
                    {
                        if (member.Type is INamedTypeSymbol { IsGenericType: true } namedType &&
                            (namedType.Name == "IDbSet" || namedType.Name == "IMutableDbSet"))
                        {
                            if (namedType.TypeArguments[0] is INamedTypeSymbol entityType)
                            {
                                types.Add(entityType);
                            }
                        }
                    }
                    return types.ToImmutable();
                })
            .SelectMany(static (types, _) => types)
            .Collect();

        context.RegisterSourceOutput(entityTypes, static (spc, types) =>
        {
            var processedTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
            var queue = new Queue<INamedTypeSymbol>();

            foreach (var type in types.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>())
            {
                queue.Enqueue(type);
            }

            while (queue.Count > 0)
            {
                var type = queue.Dequeue();
                if (!processedTypes.Add(type)) continue;

                var source = GenerateShadowStruct(type, processedTypes, queue);
                spc.AddSource($"{type.Name}_Shadow.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static string GenerateShadowStruct(INamedTypeSymbol type, HashSet<ITypeSymbol> processedTypes, Queue<INamedTypeSymbol> queue)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpArena.Collections;");
        sb.AppendLine("using SharpArena.Allocators;");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.Append("namespace ").AppendLine(ns).AppendLine("{");
        }

        var indent = ns is null ? string.Empty : "    ";
        var indent2 = indent + "    ";

        sb.Append(indent).AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.Append(indent).Append("public struct ").Append(type.Name).AppendLine("_Shadow");
        sb.Append(indent).AppendLine("{");
        
        if (type.IsReferenceType)
        {
            sb.Append(indent2).AppendLine("public bool _hasValue;");
        }

        var properties = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public)
            .Where(p => !p.GetAttributes().Any(a => a.AttributeClass?.Name == "BsonIgnoreAttribute"))
            .Where(p => !IsUnshadowable(p.Type))
            .ToList();

        foreach (var prop in properties)
        {
            var shadowType = GetShadowTypeName(prop.Type, queue);
            sb.Append(indent2).Append("public ").Append(shadowType).Append(" ").Append(prop.Name).AppendLine(";");
            if (prop.Type.IsReferenceType && prop.Type.SpecialType != SpecialType.System_String && !IsCollection(prop.Type))
            {
                sb.Append(indent2).Append("public bool HasValue_").Append(prop.Name).AppendLine(";");
            }
        }

        sb.Append(indent).AppendLine("}");
        sb.AppendLine();

        sb.Append(indent).Append("public static unsafe class ").Append(type.Name).AppendLine("_ShadowExtensions");
        sb.Append(indent).AppendLine("{");

        // From method
        sb.Append(indent2).Append("public static void From(this ref ").Append(type.Name).Append("_Shadow shadow, ")
          .Append(type.ToDisplayString()).AppendLine(" source, ArenaAllocator arena)");
        sb.Append(indent2).AppendLine("{");
        if (type.IsReferenceType)
        {
            sb.Append(indent2).AppendLine("    shadow._hasValue = true;");
        }
        foreach (var prop in properties)
        {
            GenerateFromAssignment(sb, indent2 + "    ", prop, "shadow", "source", queue);
        }
        sb.Append(indent2).AppendLine("}");
        sb.AppendLine();

        // IsDirty method
        sb.Append(indent2).Append("public static bool IsDirty(this ref ").Append(type.Name).Append("_Shadow shadow, ")
          .Append(type.ToDisplayString()).AppendLine(" current)");
        sb.Append(indent2).AppendLine("{");
        if (type.IsReferenceType)
        {
            sb.Append(indent2).AppendLine("    if (current == null) return shadow._hasValue;");
            sb.Append(indent2).AppendLine("    if (!shadow._hasValue) return true;");
        }
        foreach (var prop in properties)
        {
            GenerateIsDirtyCheck(sb, indent2 + "    ", prop, "shadow", "current", queue);
        }
        sb.Append(indent2).AppendLine("    return false;");
        sb.Append(indent2).AppendLine("}");
        sb.AppendLine();

        // ExtractChanges method
        sb.Append(indent2).Append("public static global::MongoDB.Driver.UpdateDefinition<").Append(type.ToDisplayString()).Append(">? ExtractChanges(this ref ")
          .Append(type.Name).Append("_Shadow shadow, ").Append(type.ToDisplayString()).AppendLine(" current)");
        sb.Append(indent2).AppendLine("{");
        sb.Append(indent2).AppendLine("    global::MongoDB.Driver.UpdateDefinition<").Append(type.ToDisplayString()).AppendLine(">? update = null;");
        sb.Append(indent2).AppendLine("    var builder = global::MongoDB.Driver.Builders<").Append(type.ToDisplayString()).AppendLine(">.Update;");
        sb.AppendLine();

        foreach (var prop in properties)
        {
            var name = prop.Name;
            sb.Append(indent2).Append("    {"); // Start property scope
            sb.AppendLine();
            
            // Check if property is dirty
            sb.Append(indent2).Append("        bool dirty = false;");
            sb.AppendLine();
            GenerateIsDirtyCheck(sb, indent2 + "        ", prop, "shadow", "current", queue, outDirtyVar: "dirty");
            
            sb.Append(indent2).AppendLine("        if (dirty)");
            sb.Append(indent2).AppendLine("        {");
            sb.Append(indent2).Append("            if (update == null) update = builder.Set(x => x.").Append(name).AppendLine(", current.").Append(name).AppendLine(");");
            sb.Append(indent2).Append("            else update = builder.Combine(update, builder.Set(x => x.").Append(name).AppendLine(", current.").Append(name).AppendLine("));");
            sb.Append(indent2).AppendLine("        }");
            sb.Append(indent2).AppendLine("    }");
        }

        sb.Append(indent2).AppendLine("    return update;");
        sb.Append(indent2).AppendLine("}");

        sb.Append(indent).AppendLine("}");

        if (ns is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GetShadowTypeName(ITypeSymbol type, Queue<INamedTypeSymbol> queue)
    {
        if (type.SpecialType == SpecialType.System_String)
            return "global::MongoZen.Collections.ArenaString";

        if (IsPrimitive(type))
            return type.ToDisplayString();

        if (type is INamedTypeSymbol namedType)
        {
            if (IsDictionary(namedType))
            {
                var keyType = namedType.TypeArguments[0];
                var valueType = namedType.TypeArguments[1];
                
                return $"global::MongoZen.Collections.ArenaDictionary<{GetShadowTypeName(keyType, queue)}, {GetShadowTypeName(valueType, queue)}>";
            }

            if (IsCollection(namedType))
            {
                var elementType = namedType.TypeArguments[0];
                return $"SharpArena.Collections.ArenaList<{GetShadowTypeName(elementType, queue)}>";
            }

            if (type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct)
            {
                queue.Enqueue(namedType);
                return namedType.Name + "_Shadow";
            }
        }

        if (type is IArrayTypeSymbol arrayType)
        {
            return $"SharpArena.Collections.ArenaList<{GetShadowTypeName(arrayType.ElementType, queue)}>";
        }

        return type.ToDisplayString();
    }

    private static bool IsPrimitive(ITypeSymbol type)
    {
        // IMPORTANT guard ordering: callers must check for System.String BEFORE calling
        // IsPrimitive, because string has SpecialType != None and would be treated as a
        // primitive here (direct copy / != comparison), which would produce incorrect
        // reference-equality comparisons for dirty-checking. GetShadowTypeName and
        // GenerateValueDirtyCheck both guard string first.
        if (type.SpecialType != SpecialType.None) return true;
        if (type.TypeKind == TypeKind.Enum) return true;
        // Treat BSON value types (ObjectId, Decimal128, etc.) as primitives — direct copy is safe.
        // BSON reference types (BsonDocument, BsonArray, etc.) are NOT primitives: copying the
        // reference would make the shadow alias the live object, defeating dirty-checking.
        if (type.IsValueType && type.ContainingNamespace?.ToDisplayString().StartsWith("MongoDB.Bson") == true) return true;
        return false;
    }

    private static bool IsPolymorphic(ITypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Interface) return true;
        if (type.IsAbstract) return true;
        if (type.SpecialType == SpecialType.System_Object) return true;
        if (type.GetAttributes().Any(a => a.AttributeClass?.Name == "BsonKnownTypesAttribute" || a.AttributeClass?.Name == "BsonKnownTypes")) return true;
        return false;
    }

    private static bool IsUnshadowable(ITypeSymbol type)
    {
        // BSON reference types (like BsonDocument, BsonArray) cannot be shadowed because copying the 
        // reference defeats dirty-checking, and deep-shadowing them is complex and unsafe.
        if (!type.IsValueType && type.ContainingNamespace?.ToDisplayString().StartsWith("MongoDB.Bson") == true) return true;
        if (IsPolymorphic(type)) return true;
        return false;
    }

    private static bool IsCollection(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol) return true;
        if (type is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var name = namedType.Name;
            return name == "List" || name == "IEnumerable" || name == "ICollection" || name == "IList" || name == "IReadOnlyList" || name == "IReadOnlyCollection";
        }
        return false;
    }

    private static bool IsDictionary(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var name = namedType.Name;
            return name == "Dictionary" || name == "IDictionary" || name == "IReadOnlyDictionary";
        }
        return false;
    }

    private static void GenerateFromAssignment(StringBuilder sb, string indent, IPropertySymbol prop, string target, string source, Queue<INamedTypeSymbol> queue)
    {
        var name = prop.Name;
        var targetExpr = $"{target}.{name}";
        var sourceExpr = $"{source}.{name}";
        
        if (prop.Type.IsReferenceType && prop.Type.SpecialType != SpecialType.System_String && !IsCollection(prop.Type) && !IsDictionary(prop.Type))
        {
            sb.Append(indent).Append("if (").Append(sourceExpr).AppendLine(" != null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    ").Append(target).Append(".HasValue_").Append(name).AppendLine(" = true;");
            GenerateValueAssignment(sb, indent + "    ", prop.Type, targetExpr, sourceExpr, queue);
            sb.Append(indent).AppendLine("}");
        }
        else
        {
            GenerateValueAssignment(sb, indent, prop.Type, targetExpr, sourceExpr, queue);
        }
    }

    private static void GenerateValueAssignment(StringBuilder sb, string indent, ITypeSymbol type, string targetExpr, string sourceExpr, Queue<INamedTypeSymbol> queue)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            sb.Append(indent).Append(targetExpr).Append(" = global::MongoZen.Collections.ArenaString.Clone(").Append(sourceExpr).AppendLine(", arena);");
        }
        else if (IsPrimitive(type))
        {
            sb.Append(indent).Append(targetExpr).Append(" = ").Append(sourceExpr).AppendLine(";");
        }
        else if (IsDictionary(type))
        {
            var namedType = (INamedTypeSymbol)type;
            var keyType = namedType.TypeArguments[0];
            var valueType = namedType.TypeArguments[1];
            var shadowKeyType = GetShadowTypeName(keyType, queue);
            var shadowValueType = GetShadowTypeName(valueType, queue);
            var shadowType = GetShadowTypeName(type, queue);

            sb.Append(indent).Append("if (").Append(sourceExpr).AppendLine(" != null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    var count = ").Append(sourceExpr).AppendLine(".Count;");
            sb.Append(indent).Append("    ").Append(targetExpr).Append(" = new ").Append(shadowType).AppendLine("(arena, count);");
            sb.Append(indent).Append("    foreach (var kvp in ").Append(sourceExpr).AppendLine(")");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        {"); // Add scope
            GenerateValueAssignment(sb, indent + "            ", keyType, "var shadowKey", "kvp.Key", queue);
            GenerateValueAssignment(sb, indent + "            ", valueType, "var shadowValue", "kvp.Value", queue);
            sb.Append(indent).Append("            ").Append(targetExpr).AppendLine(".AddOrUpdate(shadowKey, shadowValue);");
            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
        }
        else if (IsCollection(type))
        {
            ITypeSymbol elementType;
            if (type is IArrayTypeSymbol arrayType) elementType = arrayType.ElementType;
            else elementType = ((INamedTypeSymbol)type).TypeArguments[0];

            var shadowElemType = GetShadowTypeName(elementType, queue);

            sb.Append(indent).Append("if (").Append(sourceExpr).AppendLine(" != null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    var count = System.Linq.Enumerable.Count<").Append(elementType.ToDisplayString()).Append(">(").Append(sourceExpr).AppendLine(");");
            sb.Append(indent).Append("    ").Append(targetExpr).Append(" = new SharpArena.Collections.ArenaList<").Append(shadowElemType).AppendLine(">(arena, count);");
            sb.Append(indent).Append("    foreach (var item in ").Append(sourceExpr).AppendLine(")");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        {"); // Add scope
            GenerateValueAssignment(sb, indent + "            ", elementType, "var shadowItem", "item", queue);
            sb.Append(indent).Append("            ").Append(targetExpr).AppendLine(".Add(shadowItem);");
            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
        }
        else if (type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct)
        {
            var namedType = (INamedTypeSymbol)type;
            queue.Enqueue(namedType);
            if (targetExpr.StartsWith("var "))
            {
                 var varName = targetExpr.Substring(4);
                 sb.Append(indent).Append("var ").Append(varName).Append(" = default(").Append(namedType.Name).AppendLine("_Shadow);");
                 sb.Append(indent).Append("if (").Append(sourceExpr).AppendLine(" != null) {");
                 sb.Append(indent).Append("    ").Append(varName).Append(".From(").Append(sourceExpr).AppendLine(", arena);");
                 sb.Append(indent).AppendLine("}");
            }
            else
            {
                sb.Append(indent).Append("if (").Append(sourceExpr).AppendLine(" != null) {");
                sb.Append(indent).Append("    ").Append(targetExpr).Append(".From(").Append(sourceExpr).AppendLine(", arena);");
                sb.Append(indent).AppendLine("}");
            }
        }
    }

    private static void GenerateIsDirtyCheck(StringBuilder sb, string indent, IPropertySymbol prop, string shadow, string current, Queue<INamedTypeSymbol> queue, string? outDirtyVar = null)
    {
        var name = prop.Name;
        var shadowExpr = $"{shadow}.{name}";
        var currentExpr = $"{current}.{name}";

        if (prop.Type.IsReferenceType && prop.Type.SpecialType != SpecialType.System_String && !IsCollection(prop.Type) && !IsDictionary(prop.Type))
        {
            sb.Append(indent).Append("if (").Append(currentExpr).AppendLine(" == null)");
            sb.Append(indent).AppendLine("{");
            if (outDirtyVar != null)
                sb.Append(indent).Append("    if (").Append(shadow).Append(".HasValue_").Append(name).Append(") ").Append(outDirtyVar).AppendLine(" = true;");
            else
                sb.Append(indent).Append("    if (").Append(shadow).Append(".HasValue_").Append(name).AppendLine(") return true;");
            sb.Append(indent).AppendLine("}");
            sb.Append(indent).AppendLine("else");
            sb.Append(indent).AppendLine("{");
            if (outDirtyVar != null)
                sb.Append(indent).Append("    if (!").Append(shadow).Append(".HasValue_").Append(name).Append(") ").Append(outDirtyVar).AppendLine(" = true;");
            else
                sb.Append(indent).Append("    if (!").Append(shadow).Append(".HasValue_").Append(name).AppendLine(") return true;");
            GenerateValueDirtyCheck(sb, indent + "    ", prop.Type, shadowExpr, currentExpr, queue, outDirtyVar);
            sb.Append(indent).AppendLine("}");
        }
        else
        {
            GenerateValueDirtyCheck(sb, indent, prop.Type, shadowExpr, currentExpr, queue, outDirtyVar);
        }
    }

    private static void GenerateValueDirtyCheck(StringBuilder sb, string indent, ITypeSymbol type, string shadowExpr, string currentExpr, Queue<INamedTypeSymbol> queue, string? outDirtyVar = null)
    {
        string emitAction = outDirtyVar != null ? $"{outDirtyVar} = true" : "return true";

        if (type.SpecialType == SpecialType.System_String)
        {
            sb.Append(indent).Append("if (!").Append(shadowExpr).Append(".Equals(").Append(currentExpr).Append(")) ").Append(emitAction).AppendLine(";");
        }
        else if (IsPrimitive(type))
        {
            sb.Append(indent).Append("if (").Append(shadowExpr).Append(" != ").Append(currentExpr).Append(") ").Append(emitAction).AppendLine(";");
        }
        else if (IsDictionary(type))
        {
            var namedType = (INamedTypeSymbol)type;
            var keyType = namedType.TypeArguments[0];
            var valueType = namedType.TypeArguments[1];
            var shadowType = GetShadowTypeName(type, queue);

            sb.Append(indent).Append("if (").Append(currentExpr).AppendLine(" == null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (").Append(shadowExpr).Append(".Count > 0) ").Append(emitAction).AppendLine(";");
            sb.Append(indent).AppendLine("}");
            sb.Append(indent).AppendLine("else");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (").Append(shadowExpr).Append(".Count != ").Append(currentExpr).Append(".Count) ").Append(emitAction).AppendLine(";");
            sb.Append(indent).Append("    foreach (var kvp in ").Append(currentExpr).AppendLine(")");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        {"); // Add scope
            if (keyType.SpecialType == SpecialType.System_String)
            {
                // Use the optimized string lookup
                sb.Append(indent).Append("            if (!").Append(shadowExpr).Append(".TryGetValue(kvp.Key, out var shadowValue)) { ").Append(emitAction).AppendLine("; break; }");
            }
            else
            {
                GenerateValueAssignment(sb, indent + "            ", keyType, "var currentKey", "kvp.Key", queue);
                sb.Append(indent).Append("            if (!").Append(shadowExpr).Append(".TryGetValue(currentKey, out var shadowValue)) { ").Append(emitAction).AppendLine("; break; }");
            }
            GenerateValueDirtyCheck(sb, indent + "            ", valueType, "shadowValue", "kvp.Value", queue, outDirtyVar);
            if (outDirtyVar != null)
            {
                sb.Append(indent).Append("            if (").Append(outDirtyVar).AppendLine(") break;");
            }
            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
            }
            else if (IsCollection(type))
            {
            sb.Append(indent).Append("if (").Append(currentExpr).AppendLine(" == null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (").Append(shadowExpr).Append(".Length > 0) ").Append(emitAction).AppendLine(";");
            sb.Append(indent).AppendLine("}");
            sb.Append(indent).AppendLine("else");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (").Append(shadowExpr).Append(".Length != System.Linq.Enumerable.Count(").Append(currentExpr).Append(")) ").Append(emitAction).AppendLine(";");
            sb.Append(indent).AppendLine("    int i = 0;");
            sb.Append(indent).Append("    foreach (var item in ").Append(currentExpr).AppendLine(")");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        {"); // Add scope
            ITypeSymbol elementType;
            if (type is IArrayTypeSymbol arrayType) elementType = arrayType.ElementType;
            else elementType = ((INamedTypeSymbol)type).TypeArguments[0];
            GenerateValueDirtyCheck(sb, indent + "            ", elementType, $"{shadowExpr}[i]", "item", queue, outDirtyVar);
            if (outDirtyVar != null)
            {
                sb.Append(indent).Append("            if (").Append(outDirtyVar).AppendLine(") break;");
            }
            sb.Append(indent).AppendLine("            i++;");
            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
            }
            else if (type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct)
            {
            sb.Append(indent).Append("if (").Append(shadowExpr).Append(".IsDirty(").Append(currentExpr).Append(")) ").Append(emitAction).AppendLine(";");
            }    }

    private static void GenerateEqualityCheck(StringBuilder sb, ITypeSymbol type, string shadowExpr, string currentExpr)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            sb.Append(shadowExpr).Append(".Equals(").Append(currentExpr).Append(")");
        }
        else if (IsPrimitive(type))
        {
            sb.Append(shadowExpr).Append(" == ").Append(currentExpr);
        }
        else
        {
            // For complex keys (not typical but possible), we'd need more logic.
            // For now, assume primitives or strings for keys.
            sb.Append(shadowExpr).Append(".Equals(").Append(currentExpr).Append(")");
        }
    }
}
