using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MongoZen.SourceGenerator;

[Generator]
public sealed class ShadowStructsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all entity types used in IDbSet<T> within a DbContext
        var entityTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (ctx, ct) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    if (ctx.SemanticModel.GetDeclaredSymbol(cds, ct) is not INamedTypeSymbol symbol)
                    {
                        return ImmutableArray<INamedTypeSymbol>.Empty;
                    }

                    if (!Utils.InheritsFrom(symbol, "DbContext") || symbol.IsAbstract)
                    {
                        return ImmutableArray<INamedTypeSymbol>.Empty;
                    }

                    var types = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
                    foreach (var member in symbol.GetMembers().OfType<IPropertySymbol>())
                    {
                        if (member.Type is INamedTypeSymbol { IsGenericType: true } namedType &&
                            (namedType.Name == "IDbSet" || namedType.Name == "IMutableDbSet"))
                        {
                            if (namedType.TypeArguments[0] is INamedTypeSymbol entityType)
                            {
                                types.Add(entityType);
                            }
                        }
                    }
                    return types.ToImmutable();
                })
            .SelectMany(static (types, _) => types)
            .Collect();

        context.RegisterSourceOutput(entityTypes, static (spc, types) =>
        {
            var processedTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
            var queue = new Queue<INamedTypeSymbol>();

            foreach (var type in types.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>())
            {
                queue.Enqueue(type);
            }

            while (queue.Count > 0)
            {
                var type = queue.Dequeue();
                if (!processedTypes.Add(type)) continue;

                var source = GenerateShadowStruct(type, processedTypes, queue);
                spc.AddSource($"{type.Name}_Shadow.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static string GenerateShadowStruct(INamedTypeSymbol type, HashSet<ITypeSymbol> processedTypes, Queue<INamedTypeSymbol> queue)
    {
        var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using SharpArena.Collections;");
        sb.AppendLine("using SharpArena.Allocators;");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.Append("namespace ").AppendLine(ns).AppendLine("{");
        }

        var indent = ns is null ? string.Empty : "    ";
        var indent2 = indent + "    ";

        sb.Append(indent).AppendLine("[StructLayout(LayoutKind.Sequential)]");
        sb.Append(indent).Append("public struct ").Append(type.Name).AppendLine("_Shadow");
        sb.Append(indent).AppendLine("{");

        var properties = type.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public)
            .ToList();

        foreach (var prop in properties)
        {
            var shadowType = GetShadowTypeName(prop.Type, queue);
            sb.Append(indent2).Append("public ").Append(shadowType).Append(" ").Append(prop.Name).AppendLine(";");
            if (prop.Type.IsReferenceType && prop.Type.SpecialType != SpecialType.System_String && !IsCollection(prop.Type))
            {
                sb.Append(indent2).Append("public bool HasValue_").Append(prop.Name).AppendLine(";");
            }
        }

        sb.Append(indent).AppendLine("}");
        sb.AppendLine();

        sb.Append(indent).Append("public static unsafe class ").Append(type.Name).AppendLine("_ShadowExtensions");
        sb.Append(indent).AppendLine("{");

        // From method
        sb.Append(indent2).Append("public static void From(this ref ").Append(type.Name).Append("_Shadow shadow, ")
          .Append(type.ToDisplayString()).AppendLine(" source, ArenaAllocator arena)");
        sb.Append(indent2).AppendLine("{");
        foreach (var prop in properties)
        {
            GenerateFromAssignment(sb, indent2 + "    ", prop, "shadow", "source", queue);
        }
        sb.Append(indent2).AppendLine("}");
        sb.AppendLine();

        // IsDirty method
        sb.Append(indent2).Append("public static bool IsDirty(this ref ").Append(type.Name).Append("_Shadow shadow, ")
          .Append(type.ToDisplayString()).AppendLine(" current)");
        sb.Append(indent2).AppendLine("{");
        foreach (var prop in properties)
        {
            GenerateIsDirtyCheck(sb, indent2 + "    ", prop, "shadow", "current", queue);
        }
        sb.Append(indent2).AppendLine("    return false;");
        sb.Append(indent2).AppendLine("}");

        sb.Append(indent).AppendLine("}");

        if (ns is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string GetShadowTypeName(ITypeSymbol type, Queue<INamedTypeSymbol> queue)
    {
        if (type.SpecialType == SpecialType.System_String)
            return "SharpArena.Collections.ArenaString";

        if (IsPrimitive(type))
            return type.ToDisplayString();

        if (type is INamedTypeSymbol namedType)
        {
            if (IsCollection(namedType))
            {
                var elementType = namedType.TypeArguments[0];
                return $"SharpArena.Collections.ArenaList<{GetShadowTypeName(elementType, queue)}>";
            }

            if (type.TypeKind == TypeKind.Class || type.TypeKind == TypeKind.Struct)
            {
                queue.Enqueue(namedType);
                return namedType.Name + "_Shadow";
            }
        }

        if (type is IArrayTypeSymbol arrayType)
        {
            return $"SharpArena.Collections.ArenaList<{GetShadowTypeName(arrayType.ElementType, queue)}>";
        }

        return type.ToDisplayString();
    }

    private static bool IsPrimitive(ITypeSymbol type)
    {
        return type.IsValueType && (type.SpecialType != SpecialType.None || type.TypeKind == TypeKind.Enum);
    }

    private static bool IsCollection(ITypeSymbol type)
    {
        if (type is IArrayTypeSymbol) return true;
        if (type is INamedTypeSymbol namedType && namedType.IsGenericType)
        {
            var name = namedType.Name;
            return name == "List" || name == "IEnumerable" || name == "ICollection" || name == "IList" || name == "IReadOnlyList" || name == "IReadOnlyCollection";
        }
        return false;
    }

    private static void GenerateFromAssignment(StringBuilder sb, string indent, IPropertySymbol prop, string target, string source, Queue<INamedTypeSymbol> queue)
    {
        var name = prop.Name;
        if (prop.Type.SpecialType == SpecialType.System_String)
        {
            sb.Append(indent).Append(target).Append(".").Append(name).Append(" = SharpArena.Collections.ArenaString.Clone(").Append(source).Append(".").Append(name).AppendLine(", arena);");
        }
        else if (IsPrimitive(prop.Type))
        {
            sb.Append(indent).Append(target).Append(".").Append(name).Append(" = ").Append(source).Append(".").Append(name).AppendLine(";");
        }
        else if (IsCollection(prop.Type))
        {
            ITypeSymbol elementType;
            if (prop.Type is IArrayTypeSymbol arrayType) elementType = arrayType.ElementType;
            else elementType = ((INamedTypeSymbol)prop.Type).TypeArguments[0];

            var shadowElemType = GetShadowTypeName(elementType, queue);

            sb.Append(indent).Append("if (").Append(source).Append(".").Append(name).AppendLine(" != null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    var count = System.Linq.Enumerable.Count(").Append(source).Append(".").Append(name).AppendLine(");");
            sb.Append(indent).Append("    ").Append(target).Append(".").Append(name).Append(" = new SharpArena.Collections.ArenaList<").Append(shadowElemType).AppendLine(">(arena, count);");
            sb.Append(indent).Append("    foreach (var item in ").Append(source).Append(".").Append(name).AppendLine(")");
            sb.Append(indent).AppendLine("    {");
            if (elementType.SpecialType == SpecialType.System_String)
            {
                sb.Append(indent).Append("        ").Append(target).Append(".").Append(name).AppendLine(".Add(SharpArena.Collections.ArenaString.Clone(item, arena));");
            }
            else if (IsPrimitive(elementType))
            {
                sb.Append(indent).Append("        ").Append(target).Append(".").Append(name).AppendLine(".Add(item);");
            }
            else
            {
                sb.Append(indent).Append("        var shadowItem = default(").Append(shadowElemType).AppendLine(");");
                sb.Append(indent).AppendLine("        if (item != null) {");
                sb.Append(indent).AppendLine("            shadowItem.From(item, arena);");
                sb.Append(indent).AppendLine("        }");
                sb.Append(indent).Append("        ").Append(target).Append(".").Append(name).AppendLine(".Add(shadowItem);");
            }
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
        }
        else if (prop.Type.TypeKind == TypeKind.Class || prop.Type.TypeKind == TypeKind.Struct)
        {
            sb.Append(indent).Append("if (").Append(source).Append(".").Append(name).AppendLine(" != null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    ").Append(target).Append(".HasValue_").Append(name).AppendLine(" = true;");
            sb.Append(indent).Append("    ").Append(target).Append(".").Append(name).Append(".From(").Append(source).Append(".").Append(name).AppendLine(", arena);");
            sb.Append(indent).AppendLine("}");
        }
    }

    private static void GenerateIsDirtyCheck(StringBuilder sb, string indent, IPropertySymbol prop, string shadow, string current, Queue<INamedTypeSymbol> queue)
    {
        var name = prop.Name;
        if (prop.Type.SpecialType == SpecialType.System_String)
        {
            sb.Append(indent).Append("if (!").Append(shadow).Append(".").Append(name).Append(".Equals(").Append(current).Append(".").Append(name).AppendLine(")) return true;");
        }
        else if (IsPrimitive(prop.Type))
        {
            sb.Append(indent).Append("if (").Append(shadow).Append(".").Append(name).Append(" != ").Append(current).Append(".").Append(name).AppendLine(") return true;");
        }
        else if (IsCollection(prop.Type))
        {
            sb.Append(indent).Append("if (").Append(current).Append(".").Append(name).AppendLine(" == null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (").Append(shadow).Append(".").Append(name).AppendLine(".Count > 0) return true;");
            sb.Append(indent).AppendLine("}");
            sb.Append(indent).AppendLine("else");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (").Append(shadow).Append(".").Append(name).Append(".Count != System.Linq.Enumerable.Count(").Append(current).Append(".").Append(name).AppendLine(")) return true;");
            
            ITypeSymbol elementType;
            if (prop.Type is IArrayTypeSymbol arrayType) elementType = arrayType.ElementType;
            else elementType = ((INamedTypeSymbol)prop.Type).TypeArguments[0];

            sb.Append(indent).AppendLine("    int i = 0;");
            sb.Append(indent).Append("    foreach (var item in ").Append(current).Append(".").Append(name).AppendLine(")");
            sb.Append(indent).AppendLine("    {");
            if (elementType.SpecialType == SpecialType.System_String)
            {
                sb.Append(indent).Append("        if (!").Append(shadow).Append(".").Append(name).AppendLine("[i].Equals(item)) return true;");
            }
            else if (IsPrimitive(elementType))
            {
                sb.Append(indent).Append("        if (").Append(shadow).Append(".").Append(name).AppendLine("[i] != item) return true;");
            }
            else
            {
                sb.Append(indent).Append("        if (item == null) { if (").Append(shadow).Append(".").Append(name).AppendLine("[i].IsDirty(item)) return true; }");
                sb.Append(indent).Append("        else if (").Append(shadow).Append(".").Append(name).AppendLine("[i].IsDirty(item)) return true;");
            }
            sb.Append(indent).AppendLine("        i++;");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
        }
        else if (prop.Type.TypeKind == TypeKind.Class || prop.Type.TypeKind == TypeKind.Struct)
        {
            sb.Append(indent).Append("if (").Append(current).Append(".").Append(name).AppendLine(" == null)");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (").Append(shadow).Append(".HasValue_").Append(name).AppendLine(") return true;");
            sb.Append(indent).AppendLine("}");
            sb.Append(indent).AppendLine("else");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).Append("    if (!").Append(shadow).Append(".HasValue_").Append(name).AppendLine(") return true;");
            sb.Append(indent).Append("    if (").Append(shadow).Append(".").Append(name).Append(".IsDirty(").Append(current).Append(".").Append(name).AppendLine(")) return true;");
            sb.Append(indent).AppendLine("}");
        }
    }
}
